### ISSUE TITLE
Outstanding issues following introduction of CoupleSolid, PorousSolid and CompressibleSolid.

### ISSUE THREAD

**Issue by CusiniM** [GEOS-DEV/GEOS#1508]
The introduction of  `CoupledSolid`, `PorousSolid` and `CompressibleSolid` has changed the way physics solvers interact (or should interact) with the constitutive models. The change of behaviour has only partially been addressed in PR #1455 and some outstanding issues remain:

- [x]  force flow solvers to interface with a `CompressibleSolid` to get porosity, permeability etc and remove the old wrappers for porosity, oldPorosity and referencePorosity.
- [x] Modify flow kernels to use porosity instead of `pvMultiplier` (addressed in #1311)
- [x] Create a new assembly kernel for the `PoromechanicsEmebeddedFracturesSolver` which assembles all cell-based terms, uses the `PorousSolid` and reactivate the corresponding integrated test (addressed in #1311)
- [x] make `biotCoefficient` a property varying cell by cell (addressed in #3050).
- [x] remove `PoreVolumeCompressibleSolid`
- [x] remove the old `PoroElastic` model which is still used by some solvers (i.e., `hydrofractureSolver`)
- [x] Everything new will have to be documented.

**Comment by TotoGaz** [comment]
@CusiniM is this finally done? If not, can you manage its impact/urgency/...?

**Comment by paveltomin** [comment]
@CusiniM @joshua-white @jhuang2601 can this be closed now?

**Comment by jhuang2601** [comment]
> @CusiniM @joshua-white @jhuang2601 can this be closed now?

I updated the task on `biotCoefficient` and it can be closed.
