### ISSUE TITLE
Consolidate our usage of `hypre`

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2210]
**What is the requested feature?**

The GEOSX validation cases basically use no feature of `hypre`.
But it’s our key linear algebra backend when it comes to big simulations.
This must evolve in order to provide a more reliable environment to our researchers and end-users.

**Describe the solution you'd like**

Here are some actions; feel free to extend or modify the list.
- [x] Update `geosxAts`.
Most probably by using a submodule (or some `pip` equivalent or anything else) to https://github.com/LLNL/ATS .
This will prevent any further intertwining between our devs and the main framework. This will make future upgrades easier.
_Done in https://github.com/GEOSX/GEOSX/pull/2265_
- [ ] Build integrated cases that use `hypre`. 
    - Majority of tests should have a direct solver variant, and an interactive solver variant. 
- [ ] Build a policy (and tools) that validate results because the discrepancy of the result can be bigger than for direct solvers (due to the iterative nature of the `hypre` solvers).
    - Criteria for iterative solver variant should be less exhaustive, such as norm of primary variable and iteration count information?? @castelletto1 @CusiniM please expand.
- [ ] Build “big” cases to validate the scalability.
Can we rely on (semi) analytical cases?
Do we have to play them as part of the integrated tests?
- [ ] Provide the `hypre` team with typical GEOSX validation matrix that could be directly embedded in the unit tests of `hypre`. @francoishamon
- [x] Provide the `hypre` team with automatic checks to help improve the codebase of `hypre`.
- [ ]  Create a repository containing our updated matrices, and get `hypre` tested against it.

**Comment by victorapm** [comment]
@TotoGaz please let me know how I can help

**Comment by TotoGaz** [comment]
Hello @victorapm thank you for your help!
Could you coordinate with @francoishamon to add our `GEOSX` matrices into the unit tests of `hypre`?

**Comment by CusiniM** [comment]
@TotoGaz @castelletto1 @victorapm I have started adding integratedTests that use iterative solvers. I have added 2 here: 2https://github.com/GEOS-DEV/integratedTests/pull/27. If we come up with a  list of cases I can add them.

**Comment by paveltomin** [comment]
@herve-gross this needs more attention
