### ISSUE TITLE
Import conformal faults and fracture (DFN) from vtk for serial runs

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2308]
Currently, it is possible to import faults and fractures defined in the `vtk` file, but
- The definition of the fault is tricky and uses `FIELD_DATA` instead of real `vtk` nodes, elements, etc. (see [here](https://github.com/GEOSX/GEOSX/blob/develop/inputFiles/singlePhaseFlowFractures/tShapedFracturedCube.vtk))
- Most likely won't work in parallel.

In other words, it's a valuable proof of concept that defines baselines and shows that we're able to perform an end-to-end simulation if we're able to import a fault from a file.

We need to
- Be able to define faults and fractures (DFN) in a `vtk` file in a convenient way.
- Do the full simulation.

Intermediate milestones are
 - [x] Clarify the contracts that `FaceBlockABC` (some implicit constraints need to be clarified).
_Done in https://github.com/GEOSX/GEOSX/pull/2305_
- [x] Exchange with `vtk` specialists and propose an input file format to the community.
_Done on March 2, 2023. Using a multi-block pattern looks like an interesting way to define fault, fracture, wells.
Using the multi-block pattern to define regions instead of using an attribute needs to be further evaluated.
Some question about the MPI partitioning must be answered for both use cases._
- [x] Implement the import of a DFN from `vtk`.
_Done in https://github.com/GEOSX/GEOS/pull/2345_
- [x] Implement the import of fields on DFN from `vtk`.
_Done in https://github.com/GEOSX/GEOS/pull/2345_
- [x] Improve the `generate_fracture` feature of `mesh_doctor` to support the new file format.
_Done in https://github.com/GEOSX/GEOS/pull/2274_

Relates to https://github.com/GEOS-DEV/GEOS/issues/2413 for parallel runs.
