### ISSUE TITLE
[EPIC]: Reduce Memory Footprint

### ISSUE THREAD

**Issue by rrsettgast** [GEOS-DEV/GEOS#2338]
## Description
We would like to reduce the memory footprint of GEOSX. There are several allocations that do not need to occur every simulation, and some redundant copies that should be eliminated.

 ## Work Scope
- Evaluate the various simulation types using the `-m 0.0` command line option and compile a list of allocations to target. Post targets on this issue.
- Implement conditionals s.t. the identified allocations do not occur unless needed.
- Remove copies of linear system matrix. This requires direct filling of `hypreParCSR` matrix.

 ## Issues in this EPIC
 - [ ] https://github.com/GEOSX/GEOSX/issues/2325
 - [ ] Placeholder for issue/PR to remove some of the allocations
 - [ ] Placeholder for issue/PR to remove more of the allocations
 - [ ] Placeholder for issue/PR to remove the extra copies of the system matrix.
 - [x] #2343

**Comment by XL64** [comment]
@rrsettgast Got an error after merging develop and running with -m 0.0 :
```
************************************************************************************************************************
Data repository memory allocations
                                                                                       min          max          sum
                                                                                   -----------  -----------  -----------
|
Received signal 11: Segmentation fault

 ** StackTrace of 7 frames **
Frame 0: ./bin/geosx
Frame 1: __kernel_sigtramp_rt64
Frame 2: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > 
geosx::stringutilities::toMetricPrefixString<unsigned long>(unsigned long const&)
Frame 3: geosx::dataRepository::printMemoryAllocation(geosx::dataRepository::Group const&, int, double)
Frame 4: geosx::GeosxState::initializeDataRepository()
Frame 5: main
Frame 6: /lib64/power9/libc.so.6
Frame 7: __libc_start_main
```

**Comment by rrsettgast** [comment]
@XL64 what problem are you running. what platform?

**Comment by XL64** [comment]
I am on pangea3 (power9 + NV100) running ./acous3D_abc_smoke.xml with an increased size to 100x100x100 maxTime set to 0.01

```
    sed -i -e 's/{ 5 }/{ 100 }/g' acous3D_abc_smoke.xml                                                                                                                             |Cleaning up events
    sed -i -e 's/maxTime="0.2"/maxTime="0.01"/' acous3D_small_base.xml                                                                                                              |acousticSolver, number of time steps: 10
    mpirun -np 1 ./bin/geosx -i ./acous3D_abc_smoke.xml --trace-data-migration|| exit 1
```

**Comment by XL64** [comment]
It's due to a division per 0 in toMetricPrefixString when value is == 0.
I did that :   `int const power = (value == (T)0)?1:floor( log10( std::abs( (double)value ) ) );` and it's OK. Do you want me to do a PR or do you have a better solution ?

**Comment by XL64** [comment]
It measures "only" host memory the -m 0.0 ?
