### ISSUE TITLE
[EPIC] Viscoplasticity Models

### ISSUE THREAD

**Issue by jhuang2601** [GEOS-DEV/GEOS#2401]
## Description
The goal of this issue is to keep track of all developments related to the modeling capability of viscoplasticity.

## Work Scope

- Prepare document for general theory of implemented viscoplasticity models
- Enable modeling capability for solving boundary value problems by defining and moving `timeIncrement` 
- Add analytical verifications for meaningful examples and include them into `integratedTests`
- Business justification and applications for viscoelasticity models and more sophisticated viscoplasticity models 

## Issues/PRs in this EPIC
- [x] https://github.com/GEOS-DEV/GEOS/pull/2419
- [x] https://github.com/GEOS-DEV/GEOS/pull/2377
- [x] https://github.com/GEOS-DEV/GEOS/pull/2405
- [x] https://github.com/GEOS-DEV/GEOS/pull/2611
- [x] https://github.com/GEOS-DEV/GEOS/pull/2647
- [x] https://github.com/GEOS-DEV/GEOS/pull/2696
