### ISSUE TITLE
Import conformal faults and fracture (DFN) from vtk for parallel runs

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2413]
Multiple steps are required to import the fractures in parallel.
- [x] Connect the matrix mesh to the fracture meshes.
- [x] Split the compound mesh in parallel.

Then we need to manage the ghosting information.
- [x] Be mindful of the boundary indicators computation.
- [x] Be careful about the _in between_ status of fracture 2d elements.

Tests
- [x] Perform testing on multiple cases. 

Relates to https://github.com/GEOS-DEV/GEOS/issues/2308 for serial runs.
