### ISSUE TITLE
Enable poroelastic mechanics in hydraulic fracture solver.

### ISSUE THREAD

**Issue by rrsettgast** [GEOS-DEV/GEOS#2428]
- [x] Replace solid mechanics solver with SinglePhasePoroMechanics solver (Done in PR ##2469)
- [x] Apply to KGD...test and debug (Done in PR ##2469)
- [ ]  Define pseudo-1d column problem for testing. 
- [x]  Apply to penny...test and debug  (Done in PR ##2521)
- [ ]  Test case with closely spaced parallel fractures.
- [ ]  Add tutorial example/s
