### ISSUE TITLE
[EPIC] Reduce compilation time by defining combinations of types to be dispatched on. 

### ISSUE THREAD

**Issue by CusiniM** [GEOS-DEV/GEOS#2498]
## Description
The goal of the work tracked by this EPIC is to be able to define combinations (mainly triplets) of types, e.g., {`cell_type` `fem_type`, `constitutive_model`}, that a specific solver requires its kernels to be compiled on. This would allow us to avoid compiling kernels that are effectively unused and define compilation "configurations" that could, for example, be used to have a light version of geos compiled during development.  

## Work Scope
We plan to define the list of types to be dispatched on through cmake and to implement the capabilities necessary to dispatch a list of types. 

## Issues/PR in this EPIC
- [ ]  https://github.com/GEOS-DEV/GEOS/pull/2495
- [ ] Place holder for PR in which the `cmake` logic to define types combinations is introduced.
- [ ] Place holder for PR in which the new dispatch is used in the FEM kernel launch machinery.

**Comment by wrtobin** [comment]
Just opened #2565 which adds the JSON kernel spec capability, still WIP.
