### ISSUE TITLE
[THEME] Constitutive Models

### ISSUE THREAD

**Issue by jhuang2601** [GEOS-DEV/GEOS#2534]
## Description
The goal of this issue is to keep track of all developments related to add new constitutive models in GEOS.

## Work Scope

- Prepare documents for general theory of implemented models
- Add meaningful testing examples and include them into `integratedTests`

## Issues/PRs in this THEME
- [ ] #2401 
- [ ] Temperature dependent thermal properties
- [ ] Thermal effect on plasticity model
- [ ] Stress dependent mechanical properties
