### ISSUE TITLE
[EPIC] Temperature dependent mechanical properties

### ISSUE THREAD

**Issue by jhuang2601** [GEOS-DEV/GEOS#2535]
- [x] User-input temperature dependent solid volumetric heat capacity
       https://github.com/GEOS-DEV/GEOS/pull/3088

- [x] User-input temperature dependent thermal conductivity
       https://github.com/GEOS-DEV/GEOS/pull/3135

- [x] User-input temperature dependent thermal expansion coefficient
       https://github.com/GEOS-DEV/GEOS/pull/3185

- [x] Enable THM coupling with plastic models
       https://github.com/GEOS-DEV/GEOS/pull/3413
