### ISSUE TITLE
[EPIC] transition to self-hosted runner for GitHub actions CI

### ISSUE THREAD

**Issue by rrsettgast** [GEOS-DEV/GEOS#2656]
## Description
We should use `streak.llnl.gov` as a GitHub actions runner to speed up CI and increase usability of testing.

## Issues in this EPIC
- [ ] Setup `streak.llnl.gov` as a self hosted GitHub runner.
- [ ] Enable unit test execution for cuda CI jobs
- [ ] Enable execution of integrated testing for CI jobs
- [ ] Enable rebaseline of integrated tests via a container used for CI.
