### ISSUE TITLE
[EPIC] Update TTE builds

### ISSUE THREAD

**Issue by Bubusch** [GEOS-DEV/GEOS#3172]
## Description
Update builds on TTE HPC with new machines and modules

## Work Scope
Need to update/clean host-configs and CI Job

## Issues in this EPIC
- [x] #3081 + [TPL-262](https://github.com/GEOS-DEV/thirdPartyLibs/pull/262) Create Pangea4 host-configs
- [x] [TPL-295](https://github.com/GEOS-DEV/thirdPartyLibs/pull/295) Add Pangea4 spack config
- [ ] #3561 + [TPL-296](https://github.com/GEOS-DEV/thirdPartyLibs/pull/296) Add Pangea4 CI Job (spack based)
- [ ] TODO +  [TPL-302](https://github.com/GEOS-DEV/thirdPartyLibs/pull/302) Update Pangea3 CI build to spack with latest available modules (>=gcc11 and >=cuda11.8)
- [x] [TPL-299](https://github.com/GEOS-DEV/thirdPartyLibs/pull/299) Add Pangea3 spack config
- [x] [TPL-257](https://github.com/GEOS-DEV/thirdPartyLibs/pull/257) Add Pangea3 CI Jobs in the github actions
- [x] [TPL-308](https://github.com/GEOS-DEV/thirdPartyLibs/pull/308) Add Pine spack config 
- [x]  #3611 Create Maple host-configs
- [x] [TPL-313](https://github.com/GEOS-DEV/thirdPartyLibs/pull/313) Add Maple spack config 
- [x]  [TPL-316](https://github.com/GEOS-DEV/thirdPartyLibs/pull/316) Add variant for CUDA stack size 
- [ ] Remove host-configs once all spack builds are OK
