### ISSUE TITLE
[EPIC] Model Initialization with Faults

### ISSUE THREAD

**Issue by jhuang2601** [GEOS-DEV/GEOS#3203]
## Description
Keep track of all developments related to model initialization with Faults

## Work Scope
- Provide different options for poromechanical model initialization
- Prepare documents for available options
- Add meaningful examples and include them into `integratedTests`

## Issues in this EPIC

1. Initialization of simple problem involving mechanics through an initialization step

- [x] Documents for gravity induced hydrostatic initialization (current default option)
       https://github.com/GEOS-DEV/GEOS/pull/3249

- [x] Documents for user specified in-situ stress/pore pressure in every cell (do not update pore pressure)
       https://github.com/GEOS-DEV/GEOS/pull/3249

- [ ] Material state being set by initial step, add full material state output and endures to next step, and displacements are set to zero

2. Initialization of simple problem from

- [ ] Prescription of user specified pore pressure
- [ ] Application of boundary conditions (e.g. constant displacement gradient to account for tectonic strain)
- [ ] Targeting in-situ stress for subset of model (e.g. stress curves along wellbore)
- [ ] Change material properties

3. Add faults to 1) and 2)
- [ ] Impose high cohesion and release
- [ ] Allow slip from beginning
- [ ] Augmented Lagrange influences the approach

4. Translate/rotate coordinate system
- [ ] Normal/tangential coordinate frame from boundary conditions
- [ ] Arbitrary coordinate frame for boundary conditions
- [ ] Arbitrary coordinate frame for any field specification (define normal/tangential for layer)
